### ISSUE TITLE
Completed module 3 assignments

### ISSUE THREAD

**Issue by Poaguek** [ds4owd-001/md-03-assignments-Poaguek#1]
@larnsce 
@sskorik01 
@mianzg 

Did I push right this time?

**Comment by sskorik01** [comment]
Hi Kasandra, yes you pushed right, congratulations for completing your module 3 assignments!

You didn't answer the question concerning the data types, are you experiencing difficulties understanding this concept? 

I can see that you understood the concepts of the course, here are a few details that you can improve for next time:

1) Make sure to use the right sign, > vs >= according to the context. 

Use `filter()` to create a subset from `penguins` that only contains gentoo penguins with a bill depth **greater than or equal** to 15.5 millimeters.

```{r}
penguins_gentoo_15_5<- penguins |> filter (species == "Gentoo", bill_depth_mm >= 15.5)
```

2) When you have several options for a variable, instead of using this
```{r}
island == "Dream"| island == "Biscoe"
``` 
use this 
```{r}
island %in% c("Dream", "Biscoe")
```

Very well done!
